/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { MotivationalContent } from "./MotivationalContent";
import { MotivationalContentCountArgs } from "./MotivationalContentCountArgs";
import { MotivationalContentFindManyArgs } from "./MotivationalContentFindManyArgs";
import { MotivationalContentFindUniqueArgs } from "./MotivationalContentFindUniqueArgs";
import { DeleteMotivationalContentArgs } from "./DeleteMotivationalContentArgs";
import { MotivationalContentService } from "../motivationalContent.service";
@graphql.Resolver(() => MotivationalContent)
export class MotivationalContentResolverBase {
  constructor(protected readonly service: MotivationalContentService) {}

  async _motivationalContentsMeta(
    @graphql.Args() args: MotivationalContentCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [MotivationalContent])
  async motivationalContents(
    @graphql.Args() args: MotivationalContentFindManyArgs
  ): Promise<MotivationalContent[]> {
    return this.service.motivationalContents(args);
  }

  @graphql.Query(() => MotivationalContent, { nullable: true })
  async motivationalContent(
    @graphql.Args() args: MotivationalContentFindUniqueArgs
  ): Promise<MotivationalContent | null> {
    const result = await this.service.motivationalContent(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => MotivationalContent)
  async deleteMotivationalContent(
    @graphql.Args() args: DeleteMotivationalContentArgs
  ): Promise<MotivationalContent | null> {
    try {
      return await this.service.deleteMotivationalContent(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
